# Generated by Django 4.1.5 on 2023-01-06 17:49

from django.db import migrations, models
import functools
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_dataset_profile_rasterdata_vectordata_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raster',
            old_name='users',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='vector',
            old_name='users',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=functools.partial(main.models.upload_to, *(), **{'path': 'profile'})),
        ),
    ]
