# Generated by Django 4.1.5 on 2023-01-06 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import functools
import main.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_alter_raster_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raster',
            name='file',
            field=models.FileField(default=1, upload_to=functools.partial(main.models.upload_to, *(), **{'path': 'raster'}), validators=[main.models.validate_file_extension_raster]),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='raster',
            name='user',
        ),
        migrations.AlterField(
            model_name='vector',
            name='file',
            field=models.FileField(default=1, upload_to=functools.partial(main.models.upload_to, *(), **{'path': 'vector'}), validators=[main.models.validate_file_extension_vector]),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='vector',
            name='user',
        ),
        migrations.AddField(
            model_name='raster',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner_raster', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vector',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner_vector', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
