# Generated by Django 4.1.5 on 2023-01-09 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rasterdata_user_vectordata_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rasterdata',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.raster'),
        ),
        migrations.AlterField(
            model_name='vectordata',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vector'),
        ),
    ]
