# Generated by Django 4.1.5 on 2023-01-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_rasterdata_file_alter_vectordata_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='vector',
            name='created',
            field=models.BooleanField(default=False),
        ),
    ]
